from src.domain.ontology.schema import SchemaRelation, SchemaStatus

BASE_TBOX_RELATIONS: list[SchemaRelation] = [
    # --- Person ---
    SchemaRelation(
        source_class="Person",
        relation_name="WORKS_AT",
        target_class="Organization",
        status=SchemaStatus.CORE,
        description="Человек работает в организации",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="LOCATED_IN",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Человек находится / проживает в месте",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="PARTICIPATED_IN",
        target_class="Event",
        status=SchemaStatus.CORE,
        description="Человек участвовал в событии",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="CREATED",
        target_class="Product",
        status=SchemaStatus.CORE,
        description="Человек создал продукт / объект",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="KNOWS",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Человек знает другого человека",
    ),
    # --- Organization ---
    SchemaRelation(
        source_class="Organization",
        relation_name="LOCATED_IN",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Организация расположена в месте",
    ),
    SchemaRelation(
        source_class="Organization",
        relation_name="PRODUCES",
        target_class="Product",
        status=SchemaStatus.CORE,
        description="Организация производит продукт",
    ),
    SchemaRelation(
        source_class="Organization",
        relation_name="PART_OF",
        target_class="Organization",
        status=SchemaStatus.CORE,
        description="Организация — часть другой организации",
    ),
    # --- Event ---
    SchemaRelation(
        source_class="Event",
        relation_name="OCCURRED_AT",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Событие произошло в месте",
    ),
    SchemaRelation(
        source_class="Event",
        relation_name="OCCURRED_ON",
        target_class="Date",
        status=SchemaStatus.CORE,
        description="Событие произошло в дату",
    ),
    SchemaRelation(
        source_class="Event",
        relation_name="INVOLVES",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Событие включает / касается человека",
    ),
    # --- Product ---
    SchemaRelation(
        source_class="Product",
        relation_name="USES",
        target_class="Concept",
        status=SchemaStatus.CORE,
        description="Продукт использует концепцию / технологию",
    ),
    SchemaRelation(
        source_class="Product",
        relation_name="PRODUCED_BY",
        target_class="Organization",
        status=SchemaStatus.CORE,
        description="Продукт произведён организацией",
    ),
    SchemaRelation(
        source_class="Product",
        relation_name="LOCATED_IN",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Продукт / объект находится в месте",
    ),
    # --- Concept ---
    SchemaRelation(
        source_class="Concept",
        relation_name="RELATED_TO",
        target_class="Concept",
        status=SchemaStatus.CORE,
        description="Концепция связана с другой концепцией",
    ),
    # --- Animal ---
    SchemaRelation(
        source_class="Animal",
        relation_name="LOCATED_IN",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Животное находится в месте",
    ),
    SchemaRelation(
        source_class="Animal",
        relation_name="INTERACTS_WITH",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Животное взаимодействует с человеком",
    ),
    SchemaRelation(
        source_class="Animal",
        relation_name="INTERACTS_WITH",
        target_class="Product",
        status=SchemaStatus.CORE,
        description="Животное взаимодействует с объектом",
    ),
    SchemaRelation(
        source_class="Animal",
        relation_name="INTERACTS_WITH",
        target_class="Animal",
        status=SchemaStatus.CORE,
        description="Животное взаимодействует с другим животным",
    ),
    # --- Универсальные ---
    SchemaRelation(
        source_class="Person",
        relation_name="INTERACTS_WITH",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Человек взаимодействует с другим человеком",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="INTERACTS_WITH",
        target_class="Animal",
        status=SchemaStatus.CORE,
        description="Человек взаимодействует с животным",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="INTERACTS_WITH",
        target_class="Product",
        status=SchemaStatus.CORE,
        description="Человек взаимодействует с объектом",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="BORN_ON",
        target_class="Date",
        status=SchemaStatus.CORE,
        description="Человек родился в указанную дату",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="HAS_ROLE",
        target_class="Role",
        status=SchemaStatus.CORE,
        description="Человек занимает определённую роль / должность",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="FAMILY_RELATION",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Семейная связь с другим человеком (родитель, супруг, ребёнок и т.д.; подтипы в будущем)",
    ),
    # --- Organization / Company ---
    SchemaRelation(
        source_class="Company",
        relation_name="FOUNDED_ON",
        target_class="Date",
        status=SchemaStatus.CORE,
        description="Компания была основана в указанную дату",
    ),
    SchemaRelation(
        source_class="Organization",
        relation_name="ACQUIRED",
        target_class="Company",
        status=SchemaStatus.CORE,
        description="Организация приобрела другую компанию",
    ),
    SchemaRelation(
        source_class="Organization",
        relation_name="EMPLOYS",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Организация нанимает / работает с человеком (инверсия WORKS_AT)",
    ),
    # --- Event ---
    SchemaRelation(
        source_class="Event",
        relation_name="STARTS_ON",
        target_class="Date",
        status=SchemaStatus.CORE,
        description="Событие началось в указанную дату",
    ),
    SchemaRelation(
        source_class="Event",
        relation_name="CAUSED_BY",
        target_class="Event",
        status=SchemaStatus.CORE,
        description="Событие вызвано другим событием (причинно-следственная связь)",
    ),
    SchemaRelation(
        source_class="Event",
        relation_name="VENUE",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Место проведения события / площадка",
    ),
    # --- Location ---
    SchemaRelation(
        source_class="Location",
        relation_name="CONTAINS",
        target_class="Location",
        status=SchemaStatus.CORE,
        description="Место содержит другое место (страна содержит город, здание содержит помещение)",
    ),
    # === ДОПОЛНИТЕЛЬНЫЕ ПОЛЕЗНЫЕ ОТНОШЕНИЯ (рекомендую добавить сразу для богатства) ===
    SchemaRelation(
        source_class="Person",
        relation_name="DIED_ON",
        target_class="Date",
        status=SchemaStatus.CORE,
        description="Человек умер в указанную дату",
    ),
    SchemaRelation(
        source_class="Person",
        relation_name="RESIDES_AT",
        target_class="Address",
        status=SchemaStatus.CORE,
        description="Человек проживает по конкретному адресу",
    ),
    SchemaRelation(
        source_class="Organization",
        relation_name="HEADQUARTERED_IN",
        target_class="Address",
        status=SchemaStatus.CORE,
        description="Головной офис организации расположен по адресу",
    ),
    SchemaRelation(
        source_class="Event",
        relation_name="ENDS_ON",
        target_class="Date",
        status=SchemaStatus.CORE,
        description="Событие закончилось в указанную дату",
    ),
    SchemaRelation(
        source_class="Project",
        relation_name="LED_BY",
        target_class="Person",
        status=SchemaStatus.CORE,
        description="Проект возглавляет человек",
    ),
    SchemaRelation(
        source_class="Document",
        relation_name="ISSUED_BY",
        target_class="Organization",
        status=SchemaStatus.CORE,
        description="Документ выпущен организацией",
    ),
]
