from abc import ABC, abstractmethod

from src.domain.models.nodes import ChunkNode, DocumentNode, DocumentStats


class IDocumentRepository(ABC):
    @abstractmethod
    async def save_document(self, document: DocumentNode) -> None: ...
    @abstractmethod
    async def save_chunk(self, chunk: ChunkNode) -> None: ...
    @abstractmethod
    async def get_document_by_filename(self, filename: str) -> list[DocumentNode]: ...
    @abstractmethod
    async def get_chunks_by_document(self, doc_id: str) -> list[ChunkNode]: ...
    @abstractmethod
    async def get_all_documents_with_stats(self) -> list[DocumentStats]: ...
    @abstractmethod
    async def get_document_stats(self, doc_id: str) -> DocumentStats | None: ...
    @abstractmethod
    async def delete_document_by_filename(self, filename: str) -> bool: ...
